artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion
  source_URL: https://github.com/sanjeevmoparthi/C-Chicken_disease_classififcation_using_deepLearning_withMLDeploymentsINAWS/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
